### ISSUE TITLE
capstone2

### ISSUE THREAD

**Issue by Uthmanbello** [Uthmanbello/capstone2#21]
## Group members
There are 3 members in the group:
- Student A: Kola Kolade
- Student B: Uthman Bello
- Student C: Mark Rubanza

## The project link
https://github.com/Uthmanbello/capstone2/projects/1

**Comment by andgarzonmal** [comment]
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 Hi Team✋🏼 

#### Your project is excellent. You are almost done. However, there are some issues you should fix. Please fix them and your project will be approved.

___ 
## ♻️ Request changes ♻️

- [ ] Please  all cards need to be assigned to team members. You should see a circle with the user's avatar on each card. See the example below:

![image](https://user-images.githubusercontent.com/95243996/217281768-41429283-cb96-40a1-897e-1c885db4be98.png)

#### Here is a video explaining in more detail what you guys need to do: 

https://www.loom.com/share/a37351479fc9433aa1b83a8d306b55cf
___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by GzimAsani** [comment]
# STATUS: APPROVED :100:         
## There is nothing else to say than it's time to merge... :partying_face: 
Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


## Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- NA
### Please be reminded to not open a new pull request after you get a review, only use the same one :thought_balloon: 


 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
